from aiogram.types import InlineKeyboardButton, InlineKeyboardMarkup

b1 = InlineKeyboardButton("1-mo'jiza", callback_data="4")
b2 = InlineKeyboardButton("2-mo'jiza", callback_data="5")
b3 = InlineKeyboardButton("3-mo'jiza", callback_data="6")
b4 = InlineKeyboardButton("4-mo'jiza", callback_data="7")
b5 = InlineKeyboardButton("5-mo'jiza", callback_data="8")
b6 = InlineKeyboardButton("6-mo'jiza", callback_data="9")
b7 = InlineKeyboardButton("7-mo'jiza", callback_data="10")
b8 = InlineKeyboardButton("8-mo'jiza", callback_data="11")
b9 = InlineKeyboardButton("9-mo'jiza", callback_data="12")
b10 = InlineKeyboardButton("10-mo'jiza", callback_data="13")
b11 = InlineKeyboardButton("11-mo'jiza", callback_data="14")
b12 = InlineKeyboardButton("12-mo'jiza", callback_data="15")
b13 = InlineKeyboardButton("13-mo'jiza", callback_data="16")
b14 = InlineKeyboardButton("14-mo'jiza", callback_data="17")
b15 = InlineKeyboardButton("15-mo'jiza", callback_data="18")
b16 = InlineKeyboardButton("16-mo'jiza", callback_data="19")
b17 = InlineKeyboardButton("17-mo'jiza", callback_data="20")
b18 = InlineKeyboardButton("18-mo'jiza", callback_data="21")
b19 = InlineKeyboardButton("19-mo'jiza", callback_data="22")
b20 = InlineKeyboardButton("20-mo'jiza", callback_data="23")
b21 = InlineKeyboardButton("21-mo'jiza", callback_data="24")
b22 = InlineKeyboardButton("22-mo'jiza", callback_data="25")
b23 = InlineKeyboardButton("23-mo'jiza", callback_data="26")
b24 = InlineKeyboardButton("24-mo'jiza", callback_data="27")
b25 = InlineKeyboardButton("25-mo'jiza", callback_data="28")
b26 = InlineKeyboardButton("26-mo'jiza", callback_data="29")
b27 = InlineKeyboardButton("27-mo'jiza", callback_data="30")
b28 = InlineKeyboardButton("28-mo'jiza", callback_data="31")
b29 = InlineKeyboardButton("29-mo'jiza", callback_data="32")
b30 = InlineKeyboardButton("30-mo'jiza", callback_data="33")
b31 = InlineKeyboardButton("31-mo'jiza", callback_data="34")
b32 = InlineKeyboardButton("32-mo'jiza", callback_data="35")
b33 = InlineKeyboardButton("33-mo'jiza", callback_data="36")
b34 = InlineKeyboardButton("34-mo'jiza", callback_data="37")
b35 = InlineKeyboardButton("35-mo'jiza", callback_data="38")
b36 = InlineKeyboardButton("36-mo'jiza", callback_data="39")
b37 = InlineKeyboardButton("37-mo'jiza", callback_data="40")
b38 = InlineKeyboardButton("38-mo'jiza", callback_data="41")
b39 = InlineKeyboardButton("39-mo'jiza", callback_data="42")
b40 = InlineKeyboardButton("40-mo'jiza", callback_data="43")
b41 = InlineKeyboardButton("41-mo'jiza", callback_data="44")
b42 = InlineKeyboardButton("42-mo'jiza", callback_data="45")
b43 = InlineKeyboardButton("43-mo'jiza", callback_data="46")
b44 = InlineKeyboardButton("44-mo'jiza", callback_data="47")
b45 = InlineKeyboardButton("45-mo'jiza", callback_data="48")
b46 = InlineKeyboardButton("46-mo'jiza", callback_data="49")
b47 = InlineKeyboardButton("47-mo'jiza", callback_data="50")
b48 = InlineKeyboardButton("48-mo'jiza", callback_data="51")
b49 = InlineKeyboardButton("49-mo'jiza", callback_data="52")
b50 = InlineKeyboardButton("50-mo'jiza", callback_data="53")

mainmenu = InlineKeyboardButton("🔙 Bosh Menyu", callback_data="mainmenu")

mujizaKey = InlineKeyboardMarkup().add(b1, b2, b3).add(b4, b5, b6).add(b7, b8, b9).add(b10, b11, b12)\
    .add(b13, b14, b15).add(mainmenu)
# add(b16, b17, b18).add(b19, b20, b21).add(b22, b23, b24).add(b25, b26, b27).